### ISSUE TITLE
"NotImplementedError "

### ISSUE THREAD

**Issue by ManiBio** [fenchri/edge-oriented-graph#32]
when I am trying to run the following commands one by one  in colab:
```
!python3 eog.py --config ../configs/parameters_cdr.yaml --train --gpu -1 --early_stop
!python3 eog.py --config ../configs/parameters_cdr.yaml --train --gpu -1 --nepoch 15 --early_stop
```
I got the following error:
```
/content/edge-oriented-graph/src/converter.py:51: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays = numpy.asarray(arrays)
Traceback (most recent call last):
  File "eog.py", line 87, in <module>
    main()
  File "eog.py", line 80, in main
    train(parameters)
  File "eog.py", line 50, in train
    trainer.run()
  File "/content/edge-oriented-graph/src/nnet/trainer.py", line 140, in run
    self.train_epoch(epoch)
  File "/content/edge-oriented-graph/src/nnet/trainer.py", line 178, in train_epoch
    loss, stats, predictions, select = self.model(batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/edge-oriented-graph/src/nnet/network.py", line 305, in forward
    batch['section'], batch['distances'])
  File "/content/edge-oriented-graph/src/nnet/network.py", line 90, in graph_layer
    m_cntx = self.attention(mentions, encoded_seq[info[:, 4]], info, word_sec)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 88, in forward
    raise NotImplementedError
NotImplementedError.
```

I couldn't able to find out what kind of error is this? How do I solve this issue? 
Thank you.

**Comment by fenchri** [comment]
Hi there!

I don't think I have seen this problem before. To be honest, I've never tried the code on colab. Are you sure you are using the same PyTorch version as stated in the README?

**Comment by ManiBio** [comment]
Hi, 
I checked the torch version and I was used updated version, that's why I got the issue. Now I am using the torch version which stated in the requirements file and Now it's working fine. 
Thank you for your valuable inputs!
