### ISSUE TITLE
error happened when run sh process_cdr.sh,No such file or directory: '../data/CDR/processed/Training.data'

### ISSUE THREAD

**Issue by ghost** [fenchri/edge-oriented-graph#9]
![image](https://user-images.githubusercontent.com/25958936/70716405-4a8e6f00-1d27-11ea-8612-6f7a0cb83b0e.png)

**Comment by ghost** [comment]
Did anyone meet this error?
@fenchri

**Comment by fenchri** [comment]
Networkx is not installed. I updated the requirements.txt file. Can you please re-install the requirements and try again?
Also, make sure that 'ruby' is installed in your system.

**Comment by yangxia605** [comment]
I have the same question.and i have  installed the  Networkx.

**Comment by fenchri** [comment]
What is the exact error? Is ruby installed in your system?

**Comment by woodyXwt** [comment]
I encountered the same error, Could you provide pre-processed data?

**Comment by yangxia605** [comment]
@fenchri hi fenchri,thanks for your reply.when i. run the command of "sh process_cdr.sh";I met this error:
sh  process_cdr.sh
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/Users/mianmian/Documents/edge-oriented-graph/data_processing/tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py/geniatagger.py", line 34, in __init__
    cwd = directory
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './geniatagger': './geniatagger'
Loading examples from ../data/CDR/processed/Training.data
Traceback (most recent call last):
  File "filter_hypernyms.py", line 47, in <module>
    with open(args.input_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/processed/Training.data'
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/Users/mianmian/Documents/edge-oriented-graph/data_processing/tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py/geniatagger.py", line 34, in __init__
    cwd = directory
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './geniatagger': './geniatagger'
Loading examples from ../data/CDR/processed/Development.data
Traceback (most recent call last):
  File "filter_hypernyms.py", line 47, in <module>
    with open(args.input_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/processed/Development.data'
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/Users/mianmian/Documents/edge-oriented-graph/data_processing/tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py/geniatagger.py", line 34, in __init__
    cwd = directory
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './geniatagger': './geniatagger'
Loading examples from ../data/CDR/processed/Test.data
Traceback (most recent call last):
  File "filter_hypernyms.py", line 47, in <module>
    with open(args.input_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/processed/Test.data'
mv: rename ../data/CDR/processed/Training.data to ../data/CDR/processed/train.data: No such file or directory
mv: rename ../data/CDR/processed/Development.data to ../data/CDR/processed/dev.data: No such file or directory
mv: rename ../data/CDR/processed/Test.data to ../data/CDR/processed/test.data: No such file or directory
mv: rename ../data/CDR/processed/Training_filter.data to ../data/CDR/processed/train_filter.data: No such file or directory
mv: rename ../data/CDR/processed/Development_filter.data to ../data/CDR/processed/dev_filter.data: No such file or directory
mv: rename ../data/CDR/processed/Test_filter.data to ../data/CDR/processed/test_filter.data: No such file or directory
cat: ../data/CDR/processed/train_filter.data: No such file or directory
cat: ../data/CDR/processed/dev_filter.data: No such file or directory
➜  data_processing git:(master) ✗ export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"
➜  data_processing git:(master) ✗ sh  process_cdr.sh
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/Users/mianmian/Documents/edge-oriented-graph/data_processing/tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py/geniatagger.py", line 34, in __init__
    cwd = directory
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './geniatagger': './geniatagger'
Loading examples from ../data/CDR/processed/Training.data
Traceback (most recent call last):
  File "filter_hypernyms.py", line 47, in <module>
    with open(args.input_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/processed/Training.data'
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/Users/mianmian/Documents/edge-oriented-graph/data_processing/tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py/geniatagger.py", line 34, in __init__
    cwd = directory
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './geniatagger': './geniatagger'
Loading examples from ../data/CDR/processed/Development.data
Traceback (most recent call last):
  File "filter_hypernyms.py", line 47, in <module>
    with open(args.input_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/processed/Development.data'
Traceback (most recent call last):
  File "process.py", line 17, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/Users/mianmian/Documents/edge-oriented-graph/data_processing/tools.py", line 25, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "geniatagger"))
  File "./common/genia-tagger-py/geniatagger.py", line 34, in __init__
    cwd = directory
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/mianmian/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './geniatagger': './geniatagger'
Loading examples from ../data/CDR/processed/Test.data
Traceback (most recent call last):
  File "filter_hypernyms.py", line 47, in <module>
    with open(args.input_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/processed/Test.data'
mv: rename ../data/CDR/processed/Training.data to ../data/CDR/processed/train.data: No such file or directory
mv: rename ../data/CDR/processed/Development.data to ../data/CDR/processed/dev.data: No such file or directory
mv: rename ../data/CDR/processed/Test.data to ../data/CDR/processed/test.data: No such file or directory
mv: rename ../data/CDR/processed/Training_filter.data to ../data/CDR/processed/train_filter.data: No such file or directory
mv: rename ../data/CDR/processed/Development_filter.data to ../data/CDR/processed/dev_filter.data: No such file or directory
mv: rename ../data/CDR/processed/Test_filter.data to ../data/CDR/processed/test_filter.data: No such file or directory
cat: ../data/CDR/processed/train_filter.data: No such file or directory
cat: ../data/CDR/processed/dev_filter.data: No such file or directory

**Comment by yangxia605** [comment]
and ruby has installed in my computer
![image](https://user-images.githubusercontent.com/21167278/75651939-cc41c900-5c94-11ea-9869-b4aadf1196ea.png)

**Comment by fenchri** [comment]
This is really weird, because I re-downloaded and re-ran everything on my pc and it seems to run without a problem.

It looks like the geniatagger is not compiled correctly for your case. Can you check [this issue](https://github.com/fenchri/edge-oriented-graph/issues/14) and make sure that the `make` command did run without errors?
If yes, you should be able to see the geniatagger executable inside this directory: `data_processing/common/genia-tagger-py/geniatagger-3.0.2/`.

**Comment by yangxia605** [comment]
@fenchri hi fenchri:
Thank you for your patience and explanation,My problem is solved.And i run the make file command line by line in the terminal.I dowmload the  data from my  browser,as i copy "http://www.nactem.ac.uk/tsujii/GENIA/tagger/geniatagger-3.0.2.tar.gz" to my browser and then move it to the file.
thanks for your contribution again!!!!

**Comment by fenchri** [comment]
No problem, I am glad you solved this! 
I updated the readme file to include a solution for the changed geniatagger website.

If everyone else solved the issue as well, please close the issue :)
